### ISSUE TITLE
License violation: include picosat license

### ISSUE THREAD

**Issue by isuruf** [conda-forge/pycosat-feedstock#13]

**Comment by isuruf** [comment]
https://github.com/ContinuumIO/pycosat/blob/b38fd85b6f4dcc18efd6027e96e5785104f53bb0/picosat.h#L1-L21 is what's missing.

**Comment by ocefpaf** [comment]
@isuruf my understanding is that we should create a file with that text and include it in the recipe here as a `license_file`, right? If so I'd be happy to do it.

**Comment by isuruf** [comment]
> my understanding is that we should create a file with that text and include it in the recipe here as a license_file, right?

Yes

**Comment by jakirkham** [comment]
Are we expecting maintainers to comb through their source files to look for license headers that may have been missed? This seems to be a very difficult thing to do or enforce in practice.

**Comment by ocefpaf** [comment]
> Are we expecting maintainers to comb through their source files to look for license headers that may have been missed? This seems to be a very difficult thing to do or enforce in practice.

Indeed it is hard to enforce. I'm fixing this one though b/c it is central to everything that uses pycosat.

(As soon as I figure out how to use a list of `license_file`s when one is the the recipe and the other one is in the source code.)
